version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    restart: always
    environment:
      BIND_ADDRESS: "0.0.0.0:8080"
      DATABASE_URL: "postgres://postgres:example@db/postgres"
      RUST_LOG: "debug"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
